SEED: 223

DATASET:
#  basedir:'/Users/sungheui/PycharmProjects/basic'
  datadir: './dataset'
  num_classes: 10
  train_file: './dataset/train_file2.txt'
  train_data_file: './dataset/train_data_list.txt'
  train_label_file: './dataset/train_label_list.txt'


OPTIMIZER:
  opt_name: SGD
  params:
    lr: 0.01
    weight_decay: 0.0001

TRAINING:
  batch_size: 4 #128
  test_batch_size: 4  #256
  epochs: 100
  log_interval: 1
  use_scheduler: true
  use_wandb: true

MODEL:
  name: 'vit_base_patch8_224'
  prompt_tokens: 5
  prompt_dropout: 0.0

EXP_NAME: 'sungheui'



RESULT:
  savedir: './saved_model'
